### ISSUE TITLE
Assign requires shapes of both tensors to match, restore=False

### ISSUE THREAD

**Issue by FreakTheMighty** [tflearn/tflearn#71] opened 2016-05-13 03:41 UTC
I am attempting to "finetune" a model, and alter the last three layers of the network. The network is essentially VGG

Initially I had trained with these last three layers:

```python
network = fully_connected(network, 1024, activation='relu')
network = dropout(network, 0.5)
network = fully_connected(network, 1024, activation='relu')
network = dropout(network, 0.5)
network = fully_connected(network, 256, activation='relu')
```

I then attempted to fine tune, with these layers:

```python
network = fully_connected(network, 4096, activation='relu', restore=False)
network = dropout(network, 0.5)
network = fully_connected(network, 4096, activation='relu', restore=False)
network = dropout(network, 0.5)
network = fully_connected(network, 256, activation='relu', restore=False)
```

I get this error:
```
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3136,4096] rhs shape= [3136,1024]
```

It makes sense that the loaded model weights can't be restored onto these newly shaped layers, but I expect that was what `restore=False` would do.  Thank you in advance for the great project and whatever help you can offer.

**Comment by aymericdamien** [comment] 2016-05-13 08:14
Hi, thanks for reporting that issue! 
Actually, there was a bug and all variables were still restored. It is fixed now, please reinstall TFLearn and it should works :)

**Comment by FreakTheMighty** [comment] 2016-05-14 03:25
That did it, thank you! I noticed that it also fails to restore when I change the optimizer. Is that the expected behavior?

```
tensorflow.python.framework.errors.NotFoundError: Tensor name "Adam/Conv2D_2/W/Adam" not found in checkpoint files```

**Comment by aymericdamien** [comment] 2016-05-14 04:11
Arf.. yes, a restore argument should also be added to regression layer, so objective function or optimizer could be changed. I will work on a patch.

**Comment by aymericdamien** [comment] 2016-05-14 10:06
I released a patch, please reinstall TFLearn, and you should be able to change the optimizer.

**Closed by aymericdamien** 2016-05-14 10:06 UTC

**Comment by MrZhw** [comment] 2016-10-08 03:00
Hi, I'm using the translate model under tensorflow(0.8), and get follow error:
zeng@zeng-Aspire:~/tensorflow/tensorflow/models/rnn/translate$ python translate.py --decode --data_dir /home/zeng/data/comic/ --size=256 --num_layers=2
Reading model parameters from /home/zeng/data/comic/checkpoint/translate.ckpt-40000
Traceback (most recent call last):
  File "translate.py", line 305, in <module>
    tf.app.run()
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 300, in main
    decode()
  File "translate.py", line 232, in decode
    model = create_model(sess, True)
  File "translate.py", line 145, in create_model
    model.saver.restore(session, ckpt_path)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1090, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256,40000] rhs shape= [40000,256]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@proj_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](proj_w, save/restore_slice_29)]]
Caused by op u'save/Assign_29', defined at:
  File "translate.py", line 305, in <module>
    tf.app.run()
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 300, in main
    decode()
  File "translate.py", line 232, in decode
    model = create_model(sess, True)
  File "translate.py", line 136, in create_model
    forward_only=forward_only)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 168, in __init__
    self.saver = tf.train.Saver(tf.all_variables())
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    restore_sequentially=restore_sequentially)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 502, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 268, in _AddRestoreOps
    validate_shape=validate_shape))
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 40, in assign
    use_locking=use_locking, name=name)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
sorry, I don't understand how to fix it, where should I change

**Comment by palak-jain** [comment] 2016-11-11 11:22
Facing Similar issue. 
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [40000,256] rhs shape= [256,40000]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@proj_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](proj_w, save/restore_slice_29)]]

Note that I have created the model on tensorflow version (0.9) and loading it on (0.11). Could this be an issue?

**Comment by gsoul** [comment] 2016-11-28 11:29
Yes, it could. I just had a similar issue. In order to solve it, I copied following files from the machine where I trained the model to my local computer and it worked:
data_utils.py
seq2seq_model.py
translate.py

//and don't forget to change the import statements in the copied files

P.S. My TF versions differs from yours.

**Comment by somah1411** [comment] 2017-05-18 02:00
i have this problem 

self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [88,30] rhs shape= [631,30]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@Model/Embedding/char_embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Model/Embedding/char_embedding, save/RestoreV2)]]
